### ISSUE TITLE
iTerm2 + ohmyzsh

### ISSUE THREAD

**Issue by Kreshnik** [donnemartin/gitsome#11]
I am using `iTerm2 + ohmyzsh on OSX 10.11.4`, and I do get the following message after running `gitsome` => `zsh: command not found: gitsome`

**Comment by donnemartin** [comment]
Hi, could you post the output of:

     $ python --version

and:

     $ pip freeze

Are you installing in a `virtualenv`?

Do any of the `gh` commands work?

     $ gh trending

**Comment by Kreshnik** [comment]
I used pip3 to install gitsome, maybe this info helps.
`Python 2.7.10`

```
altgraph==0.10.2
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2016.2.28
click==6.6
dicttoxml==1.6.6
dnspython==1.12.0
Jinja2==2.8
jsonrpclib==0.1.3
livereload==2.4.1
lxml==3.4.4
macholib==1.5.1
Markdown==2.6.6
MarkupSafe==0.23
matplotlib==1.3.1
mechanize==0.2.5
mkdocs==0.15.3
mkdocs-bootstrap==0.1.1
mkdocs-bootswatch==0.4.0
modulegraph==0.10.4
numpy==1.8.0rc1
olefile==0.42.1
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
PyPDF2==1.25.1
python-dateutil==1.5
pytz==2013.7
PyYAML==3.11
requests==2.9.1
scipy==0.13.0b1
singledispatch==3.4.0.3
six==1.4.1
slowaes==0.1a1
tornado==4.3
vboxapi==1.0
xattr==0.6.4
XlsxWriter==0.7.3
zope.interface==4.1.1
```
`zsh: command not found: gh`

**Comment by donnemartin** [comment]
>`Python 2.7.10`

It does seem like `gitsome` might not have been installed properly, many of the [requirements](https://github.com/donnemartin/gitsome/blob/master/setup.py#L102-L112) are not present in your `pip freeze`.  `gitsome` requires Python 3.4 or higher.

A few things to try:

* Do you have the same issues if you run in good old Terminal?
* It might help to try and install in a [`virtualenv`](https://github.com/donnemartin/gitsome/blob/master/INSTALLATION.md), I just updated the instructions to explicitly set the Python version when creating a virtual environment

**Comment by srepollock** [comment]
You need to first install Python 3.4 from the site and run that.  
Then you need to install pip3 and install gitsome through that

`sudo pip3 install gitsome`

Worked just fine for me

**Comment by donnemartin** [comment]
Thanks @srepollock.  I think this might be a duplicate of https://github.com/donnemartin/gitsome/issues/4, there's additional information there @Kreshnik.

We added this to the README:

#### `pip3`

Depending on your system, you might need to run `pip3`, possibly with the `-H` flag:

    $ sudo -H pip3 install gitsome

For most linux users, `pip3` can be installed on your system using the `python3-pip` package. 

For example, Ubuntu users can use:

    $ sudo apt-get install python-pip3

See this [ticket](https://github.com/donnemartin/gitsome/issues/4) for more details.

**Comment by donnemartin** [comment]
@Kreshnik did this [comment](https://github.com/donnemartin/gitsome/issues/11#issuecomment-219255186) help fix your issue?

**Comment by Kreshnik** [comment]
@donnemartin, unfortunately it did not. I still get the error "zsh: command not found: gitsome"

**Comment by srepollock** [comment]
Have you upgraded pip and pip3 on your computer? As well as Python, python3? I'd use Homebrew to upgrade python and make sure that you installed the latest Python3 from the site. Next double check that oh-my-zsh is upgraded as well as iTerm2

**Comment by Kreshnik** [comment]
It works now, it was an issue with brew not being updated, and some missing links between libraries.
