### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d8/hygf80412tdgb82jxw5b_bdw0000gp/T/pip-build-qn7mlwkt/PyYAML/" 

### ISSUE THREAD

**Issue by miichan91** [donnemartin/gitsome#118]
I am trying to install Galaxy on my mac but when I try to "sh run.sh", I get this error! 

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d8/hygf80412tdgb82jxw5b_bdw0000gp/T/pip-build-qn7mlwkt/PyYAML/

Does anyone know how I can fix this?

Thanks in advance!

**Comment by donnemartin** [comment]
Hi @miichan91, I'm not sure what Galaxy is?  Could you try posting on their support channels?

Do any of these [search hits](https://www.google.com/search?q=Command+%22python+setup.py+egg_info%22+failed+with+error+code+1&oq=Command+%22python+setup.py+egg_info%22+failed+with+error+code+1&aqs=chrome..69i57j0l5.253j0j7&sourceid=chrome&ie=UTF-8) help?
