### ISSUE TITLE
gitsome currently requires Python 3.4 or 3.5

### ISSUE THREAD

**Issue by Khalian** [donnemartin/gitsome#121]
scripts python3 --version
Python 3.6.1

So I cannot use this because my python is too advanced ?

**Comment by donnemartin** [comment]
Hi @Khalian, yes gitsome is not currently compatible with 3.6.  More details [here](https://github.com/donnemartin/gitsome/issues/105).

**Comment by thieryl** [comment]
do you have any idea whenn will it be fixed?
