### ISSUE TITLE
Where is xontrib?

### ISSUE THREAD

**Issue by Khalian** [donnemartin/gitsome#124]
arunavs at f45c89bd4dd3 in /Library/Frameworks/Python.framework/Versions/3.5/bin on
$ xontrib
xonsh: subprocess mode: command not found: xontrib

**Comment by donnemartin** [comment]
Hi @Khalian, I'm not sure why you are trying to run xontrib?  Does the `gitsome` command to start the shell work?

**Comment by Khalian** [comment]
I wanted to use xontrib to add some extensions. Since gitsome has a dependency on xonsh, I presumed it also installed xontrib. That does not appear to be true.
