### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by max107** [donnemartin/gitsome#14]
:smile:

**Comment by donnemartin** [comment]
Hi Max, can you provide more details on what you're looking for?

The [GitHub Integrated commands](https://github.com/donnemartin/gitsome#github-integration) work on any shell.

Enabling tab completions can be done through [gh_complete.sh](https://github.com/donnemartin/gitsome#enabling-gh-tab-completions-outside-of-gitsome).

**Comment by max107** [comment]
@donnemartin fish shell incompatible with `gh_complete.sh`

http://stackoverflow.com/questions/20838284/how-can-i-provide-tab-completions-to-fish-shell-from-my-own-script

**Comment by benmarten** [comment]
+1 for fish shell support :)

**Comment by iliyanotlioneberia** [comment]
+1 for this idea :)

**Comment by gretel** [comment]
yay plus one 👍

**Comment by donnemartin** [comment]
>http://stackoverflow.com/questions/20838284/how-can-i-provide-tab-completions-to-fish-shell-from-my-own-script

Seems to be a popular request, marking this as help wanted if anyone wants to take a crack at it.

**Comment by deepredsky** [comment]
+1

**Comment by BarbzYHOOL** [comment]
+1

**Comment by max107** [comment]
![image](https://github.com/donnemartin/gitsome/assets/862272/85f5852c-ad9c-41d2-8b60-33c10a391ddd)
