### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in \pip-build\lwajo_46\pyproj

### ISSUE THREAD

**Issue by Tungstonia** [donnemartin/gitsome#140]
I have spend the last two days trying to install basemap to my python library. I've tried to use 'pip install [path to] basemap-1.1.0-cp36-cp36m-win_amd64.whl' but I keep getting the error of the form "Command "python setup.py egg_info" failed with error code 1 in C:\Users\MyName\AppData\Local\Temp\pip-build\lwajo_46\pyproj"

Setup tools are up to data and ez_setup has been installed. Don't know what to do from here

**Comment by donnemartin** [comment]
Hi @Tungstonia, not sure if this is gitsome related as you reference basemap.

If it is gitsome related this might be because you're running Python 3.6, which is not currently supported.  See: https://github.com/donnemartin/gitsome/issues/105
