### ISSUE TITLE
django error

### ISSUE THREAD

**Issue by omnaathharis** [donnemartin/gitsome#141]
while trying to install django in windows using pip I have encountered with this error`
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\tooti\appdata\local\temp\pip-build-z6tsd_\django\setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django\__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django\utils\version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\tooti\appdata\local\temp\pip-build-z6tsd_\django\`
how can we resolve it
Thanks and regards

**Comment by ParitoshAggarwal** [comment]
https://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c/36025294

I hope this can help you out

**Comment by donnemartin** [comment]
Hi @omnaathharis, this is not the Django project so this isn't the best place to get help.  @ParitoshAggarwal provides a link that might help.
