### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bilal\AppData\Local\Temp\pip-build-0way1c0h\tweet-preprocessor\

### ISSUE THREAD

**Issue by bilalbutt044** [donnemartin/gitsome#144]
i get this error when i run   pip install text-preprocessor 

```
C:\Users\Bilal>pip3 install tweet-preprocessor
Collecting tweet-preprocessor
  Using cached tweet-preprocessor-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bilal\AppData\Local\Temp\pip-build-0way1c0h\tweet-preprocessor\setup.py", line 6, in <module>
        long_description = f.read()
      File "c:\python\python36-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 652: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bilal\AppData\Local\Temp\pip-build-0way1c0h\tweet-preprocessor\
```

What am I doing wrong?
I am on window 10 
python  **3.6.2**
pip version **pip 9.0.1 from c:\python\python36-32\lib\site-packages (python 3.6)**

**Comment by birdsotter** [comment]
I get the same error running Python 3.6.4 and pip 9.0.1 on Mac OSX.

There are various suggested solutions at https://github.com/donnemartin/gitsome/issues/4, but none of them work for me.

It appears from some other comments that gitsome may not work yet with Python 3.6.

**Comment by roskoff** [comment]
Indeed, `gitsome` does not currently support Python 3.6, check [this comment](https://github.com/donnemartin/gitsome/issues/105#issuecomment-286078468) for more info.

**Comment by REPTILEHAUS** [comment]
Hitting this issue too, would be great to see it resolved... otherwise I wont be using it

**Comment by donnemartin** [comment]
Hi all, check out https://github.com/donnemartin/gitsome/pull/160, gitsome now supports Python 3.7.

Uploaded to PyPI: https://pypi.org/project/gitsome/
