### ISSUE TITLE
Add option to disable avatar image requests

### ISSUE THREAD

**Issue by kBite** [donnemartin/gitsome#149]
Relates to #147 and #148.

Besides the obvious use case - silencing the error message shown instead of the image (#148) - this can also improve performance depending on the user's network connection.

**Comment by Jimimaku** [comment]
> Relates to #147 and #148.
> 
> Besides the obvious use case - silencing the error message shown instead of the image (#148) - this can also improve performance depending on the user's network connection.

**Comment by Jimimaku** [comment]
> Relates to #147 and #148.
> 
> Besides the obvious use case - silencing the error message shown instead of the image (#148) - this can also improve performance depending on the user's network connection.
