### ISSUE TITLE
Support for python3.7

### ISSUE THREAD

**Issue by GreyDireWolf** [donnemartin/gitsome#152]
Currently gitsome only supports Python 3.4 or 3.5. So I'm unable to use it on Arch Linux. It would be awesome to enable support for rolling release linux distros. Does this require any significant effort?

**Comment by Jaff** [comment]
Ditto for Fedora 29

**Comment by vpassapera** [comment]
Same for osx and manjaro.

**Comment by aladagemre** [comment]
One limitation is outdated xonsh module (that is copied) which has [a recent fix](https://github.com/jaraco/xonsh/commit/5ce124a9e037fafbd57cff6e4c12783863143cd3)

It should be updated and version limitation should be [lifted](https://github.com/aladagemre/gitsome/commit/78040fe4e6595f738da50d3a4eb6ae3946c06c2c).

**Comment by donnemartin** [comment]
Hey all, sorry been really busy.  I'm starting to free up and plan to look into updating gitsome to support the latest Python versions.

**Comment by donnemartin** [comment]
Hi all, check out https://github.com/donnemartin/gitsome/pull/160, gitsome now supports Python 3.7.

Uploaded to PyPI: https://pypi.org/project/gitsome/
