### ISSUE TITLE
ZSH autocomplete 

### ISSUE THREAD

**Issue by johntdyer** [donnemartin/gitsome#2]
Any plans for zsh autocomplete ?

**Comment by donnemartin** [comment]
Yes, I'd love for `gitsome` to be an equal opportunity completer 👍

**Comment by Karunamon** [comment]
Looks like adding this is pretty simple, [thanks to a SO question](http://stackoverflow.com/questions/3249432/i-have-a-bash-tab-completion-script-is-there-a-simple-way-to-use-it-from-zsh)

In short:

* Download the `autocomplete.sh` script as mentioned in the existing docs
* Add the following to your `.zshrc`:

```sh
    autoload bashcompinit
    bashcompinit
    source autocomplete.sh
```

And then it Just Works :)

**Comment by donnemartin** [comment]
@Karunamon awesome!  Interested in submitting a pull request?  Maybe a section in the README for zsh like the following one for bash would be helpful:

https://github.com/donnemartin/gitsome#enabling-bash-completions

**Comment by donnemartin** [comment]
@johntdyer do you think the merged PR from @Karunamon is sufficient?  Or is there more we might be able to do for zsh users?

**Comment by Kmaschta** [comment]
It works well for me. Thanks!

**Comment by donnemartin** [comment]
Thanks everyone for helping out with issue!  Sounds like we can close it.
