### ISSUE TITLE
Question about auto completion

### ISSUE THREAD

**Issue by bjarneo** [donnemartin/gitsome#20]
Sorry about the generic title.

If I want to add auto completion for a cli tool I use. Should I add the code as a PR to your repo? Or do you plan to make some kind of plugin support so people doesn't pollute this repo with _everything_?

Anyways. Good work on gitsome!

**Comment by donnemartin** [comment]
Good question.  

Can the cli tool benefit from any of these?

* [Enabling Bash Completions](#enabling-bash-completions)
* [Enabling `gh` Tab Completions Outside of `gitsome`](#enabling-gh-tab-completions-outside-of-gitsome)
    * [For Zsh Users](#for-zsh-users)

If so, you could get the `gitsome` [General Autocompleter](https://github.com/donnemartin/gitsome#general-autocompleter) to kick in with some changes to your system.

For the [Autocompleter with Interactive Help](https://github.com/donnemartin/gitsome#git-and-github-autocompleter-with-interactive-help) that would require changes to the source itself.  I'd have to think about how to best expose this other commands.

**Comment by bjarneo** [comment]
@donnemartin 

Yes, it could. Followed this step: https://github.com/donnemartin/gitsome#enabling-bash-completions

Thank you :)

**Comment by donnemartin** [comment]
>Yes, it could. Followed this step: https://github.com/donnemartin/gitsome#enabling-bash-completions

Great!  I'll probably add something to the README intro area about this to make it more discoverable.

**Comment by bjarneo** [comment]
:+1: 

Want me to close the question, or should I leave it open? (other people might ask the same question)

**Comment by donnemartin** [comment]
> I'll probably add something to the README intro area about this to make it more discoverable.

I think we can leave this open until I update the README.  I might point to this issue too.  Thanks for checking.

**Comment by donnemartin** [comment]
Added README note: 6cc3ef8ba05a7215edac7e993983ddff6894021b
