### ISSUE TITLE
ZSH OSX - bashcompinit:134: parse error near `|'

### ISSUE THREAD

**Issue by theskillwithin** [donnemartin/gitsome#34]
bashcompinit:134: parse error near `|'
gh_complete.sh:8: command not found: complete

on iterm - oh my zsh - osx

.zshrc
```
autoload bashcompinit
bashcompinit
source gh_complete.sh
```

I also tried ~/gh-complete.sh

**Comment by donnemartin** [comment]
@theskillwithin it seems like you might have already seen https://github.com/donnemartin/gitsome/issues/2 which sounds similar to what @Karunamon and @Kmaschta were discussing?

I'm not a zsh user myself, hopefully someone who is might be able to tell what's wrong.

**Comment by theskillwithin** [comment]
ya I tried to look through the issues and the readme before attempting install.  

Maybe we can reach out to them here:

https://github.com/robbyrussell/oh-my-zsh

**Comment by Karunamon** [comment]
I wonder if this has something to do with zsh version... I'm also using oh-my-zsh, fully updated.

I've got `zsh 5.0.8 (x86_64-apple-darwin15.0)` from `--version`. Are you using a newer one?

**Comment by donnemartin** [comment]
@theskillwithin are you still running into issues with this?  There was a question about zsh version, did that help?

**Comment by aadfco** [comment]
If anyone is wondering on how to get rid of parse error, you need to add wp-cli to your plugins in your .zshrc profile. This is what mine looks like: 
`plugins=(
  git
  brew
  common-aliases
  node
  npm
  nvm
  rand-quote
  sudo
  yarn
  z
  colored-man-pages
  colorize
  cp
  wp-cli
  zsh-syntax-highlighting
  zsh-autosuggestions
)`

Then run `source ~/.zshrc`
