### ISSUE TITLE
Typo in the docstring

### ISSUE THREAD

**Issue by pravj** [donnemartin/gitsome#38]
In the function responsible for the command `gh feed`, the short form of the flag `--private` is written as `-p`, which is same as the flag `--pager`.

It should be replaced with its correct representation `-pr`.

You can see the typo in the [line 203](https://github.com/donnemartin/gitsome/blob/f6a3c04a4d02d57b6932d5ff0337447e8a09e00f/gitsome/githubcli.py#L203) of file `githubcli.py`.

**Comment by donnemartin** [comment]
Nice catch, this is also found in [COMMANDS.md](https://github.com/donnemartin/gitsome/blob/master/COMMANDS.md):

Usage:

    $ gh feed [user_or_repo] [-p/--private] [-p/--pager]

Can I interest you in submitting a pull request? :)

**Comment by pravj** [comment]
Yeah, I have just submitted a pull request #39.

I was looking to work on some issues so found the typo while reading the code.
But couldn't install the package because incompatible Python version.

Will try again with Python3.

**Comment by pravj** [comment]
Yeah, I have just submitted a pull request #39.

I was looking to work on some issues so found the typo while reading the code.
But couldn't install the package because incompatible Python version.

Will try again with Python3.

**Comment by donnemartin** [comment]
Sounds good, thanks @pravj.  Let me know if you need any help getting started.

Merged: https://github.com/donnemartin/gitsome/pull/39
