### ISSUE TITLE
Refactor conversion code of None to '' introduced in #40 and #49

### ISSUE THREAD

**Issue by donnemartin** [donnemartin/gitsome#52]
The fixes for the following issues were very similar and would probably be better suited as a string utility in [`TextUtils`](https://github.com/donnemartin/gitsome/blob/master/gitsome/utils.py#L28).
- [#40](https://github.com/donnemartin/gitsome/issues/40) - Fix `create-issue` `NoneType` error if no `-b/--body` is specified.
- [#49](https://github.com/donnemartin/gitsome/issues/49) - Fix `create-repo` `NoneType` error if no `-d/--description` is specified.

TODO:
- Add equivalent utility function and unit test(s).
- Update code from [#40](https://github.com/donnemartin/gitsome/issues/40)
  and [#49](https://github.com/donnemartin/gitsome/issues/49).

See https://github.com/donnemartin/gitsome/pull/50 for initial discussion.

**Comment by jashgala** [comment]
Hi, I have submitted a PR for this change. Please take a look at it. 

Thanks,
Jash

**Comment by donnemartin** [comment]
Fixed with https://github.com/donnemartin/gitsome/pull/100.
