### ISSUE TITLE
A minor typo in README

### ISSUE THREAD

**Issue by srisankethu** [donnemartin/gitsome#66]
The command under this section -> https://github.com/donnemartin/gitsome#filtering-issues should be changed from ``gh issues --issue_state open -issue_filter mentioned`` to ``gh issues --issue_state open --issue_filter mentioned``

**Comment by donnemartin** [comment]
Nice catch, are you interested in submitting a pull request?

**Comment by srisankethu** [comment]
Ya sure! I would like to help you in this project. I was thinking of building a code review github integration this summer. But i was suprised to see so many integrations already made. Can i chat with you personally? I need to an advice.

**Comment by donnemartin** [comment]
Sure, feel free to email me donne.martin@gmail.com.

**Comment by srisankethu** [comment]
Thanks! Would you be available on gitter ?
