### ISSUE TITLE
Getting  build parser error 

### ISSUE THREAD

**Issue by mridulbirla** [donnemartin/gitsome#70]
Hello, 

I am installing gitsome using "$ sudo -H pip3 install gitsome" command on my Mac but i am getting below exception. Can any help me in resolving this issue?

https://gist.github.com/mridulbirla/8fe1f17f701bf3c084419a292507993a

**Comment by donnemartin** [comment]
Hi @mridulbirla, thanks for the bug report.  

From your gist:

>installing to build/bdist.macosx-10.6-intel/wheel

Are you installing this on OS X 10.6?

It looks like you might be running Python 3.6?

Can you paste the output of `pip freeze`?

**Comment by mridulbirla** [comment]
Output of pip3 freeze : https://gist.github.com/mridulbirla/afeed7e43ca765e259d8413dafbe7a8a
OS X version: 10.11.5

**Comment by donnemartin** [comment]
Hmm, I'm not able to reproduce this.  

>virtualenv==15.0.2

I noticed you have `virtualenv` installed.  Can you try installing a fresh virtual environment to rule out potential issues with dependencies or permissions?  Here are the [virtualenv install instructions](https://github.com/donnemartin/gitsome#virtual-environment-installation).
