### ISSUE TITLE
Autocompletion of git commands cannot be enabled

### ISSUE THREAD

**Issue by gera2ld** [donnemartin/gitsome#72]
The doc says I can run `gitsome` to enable "git commands, branches, tags", but none of them is actually enabled. Do I miss something?

![1 2x](https://cloud.githubusercontent.com/assets/3139113/16867095/730e2dd6-4aa2-11e6-9337-5b0dc50b846d.png)

**Comment by donnemartin** [comment]
Hi @gera2ld,

Does this section help?  

https://github.com/donnemartin/gitsome#enabling-bash-completions

Curious if your git completions are in one of the 'default' locations gitsome looks for.

**Comment by gera2ld** [comment]
I've found the problem. Thanks for your reply.

I was using zsh. But it seems that gitsome and xonsh are based on bash, so I have to get a bash complete script and enable it for xonsh.

After adding this to `.xonshrc` it works:
```
$BASH_COMPLETIONS = ['/path/to/git-completion.bash']
```
