### ISSUE TITLE
missing context of the repo

### ISSUE THREAD

**Issue by codeHatcher** [donnemartin/gitsome#75]
The one issue I have is, is when I look for issues and I'm in a git repo on my local filesystem, I want to see those issues without having to manually specify the repo number. If everything could use that context by default, I would switch to you guys in a heartbeat.

The current one I use is https://github.com/node-gh/gh and they do that

**Comment by donnemartin** [comment]
Hi @codeHatcher, thanks for the feedback.  Is this the same request as https://github.com/donnemartin/gitsome/issues/60?

**Comment by codeHatcher** [comment]
Ah, it is. Sorry about that! I just tried to gitsome again because I forgot why I stopped using it and then thought I should give some feedback.

**Comment by donnemartin** [comment]
No problem, thanks again for the feedback.  This is something I'd like to fix.
