### ISSUE TITLE
oh-my-zsh completions?

### ISSUE THREAD

**Issue by kleerkoat** [donnemartin/gitsome#83]
how do you get autocomplete working with oh-my-zsh?

**Comment by donnemartin** [comment]
Hi @kleerkoat, I think this should help:

https://github.com/donnemartin/gitsome#for-zsh-users

If you're looking for a plugin, here's the ticket for it: https://github.com/donnemartin/gitsome/issues/35

**Comment by arpit1997** [comment]
autocomplete for [gitsome](https://github.com/donnemartin/gitsome/) already works in [oh my zsh](https://github.com/donnemartin/gitsome/) by deafult. there is no need to do anything additional for autocomplete. I am running this on 
` ` `
ubuntu 14.04

python 3.4
` ` `

**Comment by donnemartin** [comment]
@arpit1997 thanks for the info.
@kleerkoat hopefully your question was answered, closing this issue.
