### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by oguzzkilic** [donnemartin/gitsome#85]
I get an error..

`Command "python setup.py egg_info" failed with error code 1 in /var/folders/74/sgsf27_x7v72qt6pv18j52sm0000gn/T/pip-CwasZv-build/`

**Comment by donnemartin** [comment]
Hi @oguzzkilic, please check out https://github.com/donnemartin/gitsome/issues/4, which seems like the same issue?

**Comment by oguzzkilic** [comment]
Hi @donnemartin yes, my problem was solved. Thanks.

**Comment by donnemartin** [comment]
Thanks for the update!  I'll close this issue.
