### ISSUE TITLE
Duplicate Entries?

### ISSUE THREAD

**Issue by arpit1997** [donnemartin/gitsome#87]
I got some duplicate entries in the `gh search repo` command. :thinking: 
```
  98.  idan/djoosh (Python)
        Stars: 32     Forks: 1      Updated: 5 month(s) ago 
  99.  brosner/django-mailer (Python)
        Stars: 32     Forks: 7      Updated: 5 month(s) ago 
  100. alex/django-resume-builder (Python)
        Stars: 32     Forks: 4      Updated: 5 month(s) ago 
  101. alex/django-resume-builder (Python)
        Stars: 32     Forks: 4      Updated: 5 month(s) ago 
  102. drslump/pyshould (Python)
        Stars: 32     Forks: 6      Updated: 2 month(s) ago 
  103. dndx/xiamiurl (Python)
        Stars: 32     Forks: 8      Updated: 1 year(s) ago 
  104. nskrypnik/kivy3 (Python)
        Stars: 32     Forks: 14     Updated: 1 month(s) ago 
```
I don't know whether this result is mistake of application or the API, can't say if it is a mistake or not. 
Just reporting this so have a look at it. @donnemartin 
:cheese:

**Comment by donnemartin** [comment]
Hi @arpit1997, what search query did you run?  Can you run the same query on the web [GitHub Search](https://github.com/search) and compare the results with the output of `gitsome`?

**Comment by arpit1997** [comment]
I ran the following:
```
$ gh search-repos "created:<=2015-01-01 stars:<=32 language:python" --sort stars
 -p
```
I ran same query on the browser and same result there.
So i guess it came from API side and not a fault of application.
:smile: :smile_cat:

**Comment by donnemartin** [comment]
Thanks for confirming we see the same behavior with GitHub search, closing the issue.

**Comment by arpit1997** [comment]
I did not go through the code but just one suggestion - we can use a set like structure to nullify this kind of behavior. @donnemartin
